name: Email Action Test

on:
  push:
    branches:
      - main  # or 'master' if your branch is named that

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 22f2001007@ds.study.iitm.ac.in
        run: echo "Hello, world from IITM DS email!"
